services:
  edge-mining:
    restart: unless-stopped
    build:
      context: .
    ports:
      - "80:80"
    environment:
      - TIMEZONE=Europe/Rome
      - SCHEDULER_INTERVAL_SECONDS=5
      - SQLITE_DB_FILE=user_data/edgemining.db
      - YAML_POLICIES_DIR=user_data/optimization_policies
    volumes:
      - ./user_data/optimization_policies:/app/core/optimization_policies
      - ./user_data/edgemining.db:/app/core/edgemining.db

networks: {}
